"use client";

import React, { useState } from "react";
import Link from "next/link";
import { Sparkles, Download, FileText, ArrowRight, CheckCircle } from "lucide-react";

export default function BriefBuilder() {
  const [form, setForm] = useState({
    title: "",
    author: "",
    genre: "Epic Fantasy",
    tone: "Dark & Atmospheric",
    description: "",
    keyElements: "",
    colorPalette: "",
  });

  const [isGenerated, setIsGenerated] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setForm({
      ...form,
      [e.target.name]: e.target.value,
    });
  };

  const generateBriefContent = () => {
    return `# BOOK COVER DESIGN BRIEF
Generated by Mystic Vault Society Cover Brief Builder
Date: ${new Date().toLocaleDateString("en-US")}

## 📖 Book Information
- **Title**: ${form.title || "Untitled Project"}
- **Author**: ${form.author || "Anonymous"}
- **Genre**: ${form.genre}
- **Tone/Aesthetic**: ${form.tone}

## 📝 Synopsis & Core Narrative Theme
${form.description || "No synopsis provided."}

## 🎨 Creative Direction & Visual Elements
- **Key Elements to Include**: ${form.keyElements || "No key elements specified."}
- **Color Palette Preferences**: ${form.colorPalette || "No specific color palette preferences."}

---
## 🛡️ Guild Notes
This brief was compiled to help cover artists and illustrators understand the narrative atmosphere. 
Need professional consultation or artist matching? Get in touch with our design guild:
https://mysticvaultsociety.com/contact
`;
  };

  const handleDownload = () => {
    const briefText = generateBriefContent();
    const blob = new Blob([briefText], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    const safeTitle = (form.title || "Book").toLowerCase().replace(/[^a-z0-9]+/g, "-");
    link.setAttribute("download", `mvs-cover-brief-${safeTitle}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setIsGenerated(true);
  };

  return (
    <div className="w-full max-w-3xl mx-auto bg-card border border-border rounded-2xl p-6 sm:p-10 shadow-xl relative overflow-hidden crimson-glow">
      {/* Design accents */}
      <div className="absolute top-1 left-1 w-3 h-3 border-t border-l border-primary/40 rounded-tl" />
      <div className="absolute top-1 right-1 w-3 h-3 border-t border-r border-primary/40 rounded-tr" />
      <div className="absolute bottom-1 left-1 w-3 h-3 border-b border-l border-primary/40 rounded-bl" />
      <div className="absolute bottom-1 right-1 w-3 h-3 border-b border-r border-primary/40 rounded-br" />

      <div className="flex flex-col gap-6">
        <div className="flex flex-col gap-1.5">
          <span className="text-primary text-xs font-bold uppercase tracking-[0.2em] font-mono">Creative Assistant</span>
          <h2 className="text-2xl sm:text-3xl font-serif font-bold text-foreground">Book Cover Brief Builder</h2>
          <p className="text-muted-foreground text-xs sm:text-sm leading-relaxed">
            Fill out the form below to compile your cover visual requirements. Once done, download the formatted markdown brief file to send directly to illustrators, or submit it to our guild consultants.
          </p>
        </div>

        {/* Form elements */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mt-2">
          <div className="flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Book Title</label>
            <input
              type="text"
              name="title"
              value={form.title}
              onChange={handleChange}
              placeholder="e.g. Rise of the Veilbreaker"
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground"
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Author Name</label>
            <input
              type="text"
              name="author"
              value={form.author}
              onChange={handleChange}
              placeholder="e.g. Michael Schustereit"
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground"
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Genre</label>
            <select
              name="genre"
              value={form.genre}
              onChange={handleChange}
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground"
            >
              <option>Epic Fantasy</option>
              <option>Grimdark Fantasy</option>
              <option>Space Opera / Sci-Fi</option>
              <option>Cyberpunk / Dystopian</option>
              <option>Urban Fantasy / Lore</option>
            </select>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Tone &amp; Aesthetic</label>
            <select
              name="tone"
              value={form.tone}
              onChange={handleChange}
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground"
            >
              <option>Dark &amp; Atmospheric</option>
              <option>Bright &amp; Heroic</option>
              <option>Gritty &amp; Grounded</option>
              <option>Dreamy &amp; Mythological</option>
            </select>
          </div>

          <div className="md:col-span-2 flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Brief Synopsis &amp; Themes</label>
            <textarea
              name="description"
              rows={3}
              value={form.description}
              onChange={handleChange}
              placeholder="Describe the core conflict, the main character, or central themes (e.g. a knight discovering that the divinity he serves is built on deceptions)."
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground resize-none"
            />
          </div>

          <div className="md:col-span-2 flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Key Visual Elements to Include</label>
            <textarea
              name="keyElements"
              rows={2}
              value={form.keyElements}
              onChange={handleChange}
              placeholder="List specific items, symbols, or background features (e.g. glowing runes, a cracked broadsword, stormy grey skies)."
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground resize-none"
            />
          </div>

          <div className="md:col-span-2 flex flex-col gap-2">
            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Color Palette Preferences</label>
            <input
              type="text"
              name="colorPalette"
              value={form.colorPalette}
              onChange={handleChange}
              placeholder="e.g. Crimson red, obsidian black, and slate grey"
              className="px-4 py-3 bg-background border border-border rounded-xl text-sm focus:outline-none focus:border-primary transition-colors text-foreground"
            />
          </div>
        </div>

        {/* Action triggers */}
        <div className="flex flex-col sm:flex-row gap-4 mt-6 pt-6 border-t border-border/50">
          <button
            onClick={handleDownload}
            disabled={!form.title}
            className={`flex items-center justify-center gap-2 px-6 py-3.5 rounded-lg text-xs font-bold uppercase tracking-wider transition-all duration-300 w-full sm:w-auto ${
              !form.title
                ? "bg-secondary text-muted-foreground/45 cursor-not-allowed border border-border"
                : "bg-primary text-primary-foreground hover:bg-primary/95 crimson-glow"
            }`}
          >
            <Download className="w-4 h-4" />
            Download Design Brief (.md)
          </button>

          {isGenerated && (
            <Link
              href="/contact"
              className="flex items-center justify-center gap-2 px-6 py-3.5 bg-secondary text-secondary-foreground border border-primary/20 hover:border-primary/50 rounded-lg text-xs font-bold uppercase tracking-wider hover:bg-primary/10 transition-all duration-300 w-full sm:w-auto animate-in fade-in slide-in-from-left-2"
            >
              <CheckCircle className="w-4 h-4 text-primary" />
              Submit Brief to Guild
              <ArrowRight className="w-4 h-4" />
            </Link>
          )}
        </div>
      </div>
    </div>
  );
}
